add_library(mcw_net STATIC client.cpp protocol.cpp server.cpp server_commands.cpp server_world.cpp socket.cpp websocket.cpp)
target_link_libraries(mcw_net PUBLIC mcw_core mcw_data mcw_world mcw_game mcw_save PRIVATE nlohmann_json::nlohmann_json)
if(WIN32)
  target_link_libraries(mcw_net PUBLIC ws2_32 iphlpapi)
endif()
if(EMSCRIPTEN)
  target_link_options(mcw_net PUBLIC -lwebsocket.js)
endif()
mcweb_target_defaults(mcw_net)
