add_library(mcw_core STATIC buffer.cpp fs.cpp hash.cpp jobs.cpp log.cpp zip.cpp)
target_include_directories(mcw_core PUBLIC ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(mcw_core PUBLIC glm::glm PRIVATE miniz)
if(EMSCRIPTEN AND MCWEB_WEB_THREADS)
  target_compile_options(mcw_core PUBLIC -pthread)
  target_link_options(mcw_core PUBLIC -pthread)
endif()
if(NOT EMSCRIPTEN)
  find_package(Threads REQUIRED)
  target_link_libraries(mcw_core PUBLIC Threads::Threads)
endif()
mcweb_target_defaults(mcw_core)
